
package org.amdocs;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://amdocs.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "helloReturn", targetNamespace = "http://amdocs.org")
    @RequestWrapper(localName = "hello", targetNamespace = "http://amdocs.org", className = "org.amdocs.Hello_Type")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://amdocs.org", className = "org.amdocs.HelloResponse")
    public String hello();

}
